# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ceeb8a347641ba8fb698d521e140e647"
name = "x_supply_chain_x"
handle = "x_supply_chain_x"
application_url = "https://764a-222-129-52-36.ngrok-free.app"
embedded = false

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://764a-222-129-52-36.ngrok-free.app/auth/callback",
  "https://764a-222-129-52-36.ngrok-free.app/auth/shopify/callback",
  "https://764a-222-129-52-36.ngrok-free.app/api/auth/callback",
  "https://764a-222-129-52-36.ngrok-free.app/api/offline/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
